
.cpe_members: &cpeTeam
  - &Ricardo {user: Ricardo, name: Ricardo Feliciano, gitHubId: felicianotech}
  - &Adam {user: Adam, name: Adam Hartley, gitHubId: BytesGuy}
  - &Jeff {user: Jeff, name: Jeff Chen, gitHubId: Jalexchen}
  - &Kyle {user: Kyle, name: Kyle Tryon, gitHubId: KyleTryon}
  - &Brian {user: Brian, name: Brian Vu, gitHubId: brivu}
  - &Eric {user: Eric, name: Eric Ribeiro, gitHubId: EricRibeiro}
  - &Ryan {user: Ryan, name: Ryan Bourdais, gitHubId: ryanbourdais}
teams:
  images: [*Ricardo, *Adam, *Jeff, &Ryan]
  orbs: [*Kyle, *Brian, *Eric]
  cpe_team: *cpeTeam
  junior_members:
    - *Brian
    - *Eric
    - *Jeff
    - *Ryan
  senior_members:
    - *Ricardo
    - *Kyle
    - *Adam
default_team: cpe_team
orgs:
  - circleci
  - CircleCI-Public
